name: extrnalexam
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2 # Latest stable version
  firebase_auth: ^4.17.5 # Latest stable version
  cloud_firestore: ^4.17.5 # Aligning with firebase versions
  provider: ^6.1.5 # Latest stable version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
